version: "3.2"

services:
  ahpuoj:
    image: ahpuojv2-deploy
    # build: ./ahpuojv2-deploy
    tty: true
    depends_on:
      - db
    ports:
      - "80:80"
      - "8080:8080"
      - "2345:2345"
    volumes: 
      - ${OJ_WEB_PATH_HOST}:${OJ_WEB_PATH_CONTAINER}${OJ_CODE_CONTAINER_FLAG}
      - ${OJ_DATA_PATH_HOST}:${OJ_DATA_PATH_CONTAINER}${OJ_CODE_CONTAINER_FLAG}
    links:
      - db
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    privileged: true
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Shanghai